name: Convert meg4 -> bedrock pack

on:
  workflow_dispatch:
    inputs:
      file-download-url:
        description: "Link download (.zip) example: CDN discord"
        required: true
        type: string

jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow python-dotenv

      - name: Download input zip (Discord safe)
        run: |
          curl -L \
            -A "Mozilla/5.0" \
            -H "Accept: */*" \
            -o input.zip \
            "${{ inputs.file-download-url }}"
          ls -lah input.zip

      - name: Convert to Bedrock Pack
        env:
          file: input.zip
          PACK_NAME: "Converted Meg4"
          PACK_DESC: "Jung Ganmyeon moded"
        run: python main.py

      - uses: actions/upload-artifact@v4
        with:
          name: Converted_Pack
          path: Converted_Pack.mcpack
